### PR TITLE
Action clippy

### PR DESCRIPTION
**Pull request by iluminat23**

### CODE REVIEW

**Comment by iluminat23** [comment]
The action seems to work as expected: https://github.com/iluminat23/revpi-hat-eeprom/actions

**Comment by nbuchwitz** [comment]
@iluminat23, could you please add the internal reference (either to the branch name or to the title)

**Comment by iluminat23** [comment]
> @iluminat23, could you please add the internal reference (either to the branch name or to the title)

There is none ;)
I can link the ticket I am waiting on a review: REVPI-2447 (https://github.com/RevolutionPi/revpi-hat-eeprom/pull/4)

**Review by nbuchwitz — APPROVED** [review]
LGTM. I like the new world, where we create proper CI from the begin on

**Pull request merged**
